### ISSUE TITLE
Potential Bypass of Rate Limiting by Sending Identical Messages

### ISSUE THREAD

**Issue by Jin-K-Yang** [Rate-Limiting-Nullifier/rlnjs#111]
Hello,

I am learning ZK and exploring the RLN (Rate-Limiting Nullifier) protocol and came across a potential concern regarding the rate limiting mechanism.

It seems that if a user sends same messages (with the same messageId and hash value) exceeding the rate limit within a specified epoch, each message would generate the same point _(x,y)_ on the user's polynomial. As a result, despite exceeding the rate limit, the protocol would not be able to recover the user's polynomial from a single point, thus the user would not be slashed.

I would like to confirm if this behavior is indeed as described and if there are any mechanisms within the protocol to prevent this kind of abuse.

Thank you.

**Comment by mhchia** [comment]
Hey @Jin-K-Yang, yes, the behavior is expected. Protocols using RLN should be aware of this and check if *(x, y)* has been seen before when they receive an RLN proof.

For example, with RLNjs you can check a proof with [`rln.saveProof(proof)`](https://github.com/Rate-Limiting-Nullifier/rlnjs/blob/2321eb0289434fc72e8ba15adf1620ee3873f6a8/src/rln.ts#L643). If the result is [`Status.DUPLICATE`](https://github.com/Rate-Limiting-Nullifier/rlnjs/blob/2321eb0289434fc72e8ba15adf1620ee3873f6a8/src/cache.ts#L33), it means you've already done `rln.saveProof(anotherProof)` before, where `anotherProof` has the same `(x, y)` as `proof`. You can then reject the proof and do further actions, for example, ignoring this proof or banning the peer who sent the proof, etc, depending on your protocol.

**Comment by Jin-K-Yang** [comment]
Got it! Thanks for the explanation. Have you considered other methods to solve this problem? An idea that came in my head is to change the current formula `x = hash(message)` to `x = hash(message, randomNumber)`. This way, even the same message could generate two different points, and this could be built into the protocol, eliminating the need for external mechanisms to prevent this issue.

**Comment by mhchia** [comment]
> An idea that came in my head is to change the current formula x = hash(message) to x = hash(message, randomNumber)

Please let me know if I didn't get you correctly: I think it doesn't solve the issue.  `(x, y)` are public inputs of an RLN proof so that verifiers can do SSS recovery. Even if you add a random number, a malicious user can still just send the same proof that they previously generated/received to other users. Other users still need to verify proofs and check if their `(x, y)` has been used before. 

And for a prover using `rln.createProof(epoch, message)`, since there is a `messageIDCounter` in rln instance, within the same epoch every call to `createProof` [uses a different message id](https://github.com/Rate-Limiting-Nullifier/rlnjs/blob/2321eb0289434fc72e8ba15adf1620ee3873f6a8/src/rln.ts#L565), and with the same `message` yields a different `y'`, so `(x, y') != (x, y)`.

**Comment by Jin-K-Yang** [comment]
I see, I didn't consider that the user could just use the previous proof. Thanks again for your reply! it really helped me understand the protocol better.

**Comment by mhchia** [comment]
No problem, thanks for bringing up feedback! :) I'm closing this issue. Feel free to leave comments here or open a new issue if you have any questions or things to discuss further
