### ISSUE TITLE
RLN Constructor changes

### ISSUE THREAD

**Issue by AtHeartEngineer** [Rate-Limiting-Nullifier/rlnjs#57]
* Vkey shouldn't be required
* Semaphore ID - Maybe this SHOULD be required? and we can give a method using `RLN` to generate one?
* RLN AppID should also be required

**Comment by mhchia** [comment]
> Vkey shouldn't be required

Is it because it's only required when verifying a proof, i.e. a proving-only instance doesn't need a verification key?

> Semaphore ID - Maybe this SHOULD be required? and we can give a method using RLN to generate one?

Do you mean the `Identity` object? If so, I think it's required, and I wonder if it would make sense to change it from `string` to `Identity` because we don't need further `identity.toString()` if we want to use an existing `Identity`.
