### ISSUE TITLE
Refactor examples

### ISSUE THREAD

**Issue by mhchia** [Rate-Limiting-Nullifier/rlnjs#94]
## What’s wrong?
We have examples for [browser](https://github.com/Rate-Limiting-Nullifier/rlnjs/tree/main/examples/browser) and [nodejs](https://github.com/Rate-Limiting-Nullifier/rlnjs/tree/main/examples/node). They actually have common code snippets and should be able to be combined into one example, which makes it easier to maintain the code.

## How to fix it?
We can combine two examples into one, and people can just run different commands in the same example project. For instance, `npm run browser` for browser and `npm run node` for node

**Comment by mhchia** [comment]
Great, thanks! Is the issue clear enough, or something you'd like to clarify? Let me know if you encounter any issues

**Comment by 0xkf** [comment]
I would like to know more about readme of rlnjs >examples >node directory.

It describes as bottom here.
I have deployed contract, but do i have to write some script??
If possible, I would like you to tell me more about it in detail.

This is the log of contract deployment.
https://goerli.etherscan.io/tx/0xad7eabfe035c5241574a04f05d4d207f5c54e1d06f16bc665198f4a4f51ec03b　
https://goerli.etherscan.io/tx/0x3c77ca2a6931cdc7f03afc0bc9456a4ad128b5a3b4eb49ec208a0acab955a283

This is readme description.
”Example: use RLNjs in NodeJS
The example go through the following steps:
Deploy the necessary contracts: verifier (the mock proof verifier since it's not yet generated), ERC20 token, and the RLN contract
Create a RLN instance rln, and demonstrate how to register, createProof, verifyProof, withdraw, and releaseWithdrawal.
Create a RLN instance rlnAnother and demonstrate how to slash a spammer. rlnAnother simply register and send more proofs than they should. rln can detect the spam by examine the output from saveProof. If the status of the output is BREACH, the secret is leaked. rln can use the recovered secret to slash the spammer by calling slash.”
